name: update ownership records
on:
  workflow_dispatch:
    inputs:
      status:
        description: member status Member|Non-member|Deceased
        required: true
      firstname:
        description: member given name
        required: true
      lastname:
        description: member family name
        required: true
      id:
        description: member GOLD id
        required: true
      member_number:
        description: membership number
        required: false
jobs:
  boat_job:
    runs-on: ubuntu-latest
    name: A job to find boats owned and update if needed
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python -m pip install poetry==2.1.3
    - run: python -m poetry install --no-root
    - name: set branch name
      run: echo branch=member${{ github.event.inputs.id }} >> $GITHUB_ENV
    - name: create branch
      run: |
        echo new branch ${{ env.branch }}
        git branch ${{ env.branch }}
        git checkout ${{ env.branch }}
    - name: update member ownerships
      run: |
        python -m poetry run python update_member_ownerships.py ${{ github.event.inputs.status }} "${{ github.event.inputs.firstname }}" "${{ github.event.inputs.lastname }}" ${{ github.event.inputs.id }} ${{ github.event.inputs.member_number }}
        git add .
        if git diff --cached --exit-code; then
          echo CHANGES=0 >> $GITHUB_ENV
        else
          echo CHANGES=1 >> $GITHUB_ENV
        fi
        true
    - name: commit, push and create PR if changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ env.CHANGES == 1 }}
      run: |
        git config --global user.name ogauk  
        git config --global user.email boatregister@oga.org.uk
        git commit . -m "updated owners"
        git push -u origin ${{ env.branch }}
        gh pr create \
          --assignee AlisonCable \
          --base main \
          --head ${{ env.branch }} \
          --title "change to member with GOLD id ${{ github.event.inputs.id }}" \
          --body "${{ github.event.inputs.firstname }} ${{ github.event.inputs.lastname }} in membership ${{ github.event.inputs.member_number }} is ${{ github.event.inputs.status }}"